type RuntimeMap = Record<string, (...args: any[]) => any>;

let runtime: RuntimeMap = {};

export function registerAdamCopilotRuntime(nextRuntime: RuntimeMap) {
  runtime = { ...runtime, ...(nextRuntime || {}) };
}

function invoke(name: string, args: any[]) {
  const fn = runtime[name];
  if (typeof fn !== "function") {
    throw new Error(`ATOS copilot runtime not registered for ${name}`);
  }
  return fn(...args);
}

export const callRegisteredRuntime = (...args: any[]) => invoke("callRegisteredRuntime", args);
export const requestAIText = (
  system: string,
  user: string,
  options: Record<string, any> = {},
): Promise<string> => invoke("requestAIText", [system, user, options]);
export const buildCopilotAmbientContext = (...args: any[]) => invoke("buildCopilotAmbientContext", args);
export const detectCopilotRequestMode = (...args: any[]) => invoke("detectCopilotRequestMode", args);
export const generateProactiveCopilotBriefing = (...args: any[]) => invoke("generateProactiveCopilotBriefing", args);
export const applyCapturedCopilotInputs = (...args: any[]) => invoke("applyCapturedCopilotInputs", args);
export const extractDeliveryRolesFromStructuredRows = (...args: any[]) => invoke("extractDeliveryRolesFromStructuredRows", args);
export const extractDeliveryRolesFromRosterContext = (...args: any[]) => invoke("extractDeliveryRolesFromRosterContext", args);
export const extractDiscoverContextFromDocument = (...args: any[]) => invoke("extractDiscoverContextFromDocument", args);
export const captureCopilotInputs = (...args: any[]) => invoke("captureCopilotInputs", args);
export const orchestrateCopilotAgents = (...args: any[]) => invoke("orchestrateCopilotAgents", args);

export async function extractArchitectureDecisionsFromDocument(
  doc: { text?: string; name?: string },
  existingDecisions: any[] = [],
): Promise<any[]> {
  if (!doc?.text?.trim() || doc.text.trim().length < 200) return [];

  const system = `You are extracting architecture decisions from a technical document. 
For each decision found, return a JSON array of objects with: 
{ title, rationale, chosenApproach, alternativesConsidered, tradeOffs, linkedCapabilityIds: [] }
Return ONLY decisions that are explicitly stated. Do not invent. Return [] if none found.`;

  const user = doc.text.slice(0, 5000);

  try {
    const raw = await callRegisteredRuntime(system, user, { max_tokens: 1200 });
    const jsonStr = String(raw || "").match(/\[[\s\S]*\]/)?.[0];
    if (!jsonStr) return [];
    const parsed = JSON.parse(jsonStr);
    if (!Array.isArray(parsed)) return [];

    const existingTitles = new Set(
      existingDecisions.map((decision: any) => String(decision.title || "").toLowerCase().trim()),
    );

    return parsed
      .filter((decision) => decision?.title && !existingTitles.has(String(decision.title).toLowerCase().trim()))
      .map((decision) => ({
        ...decision,
        id: Math.random().toString(36).slice(2, 10),
        decision: decision?.decision || decision?.chosenApproach || "",
        decisionTitle: decision?.decisionTitle || decision?.title || "",
        chosenOption: decision?.chosenOption || decision?.chosenApproach || decision?.decision || "",
        status: "draft",
        sourceDocuments: [doc.name || "uploaded document"],
        createdAt: new Date().toISOString(),
        sourceArtifactId: null,
        sourceArtifactPhase: null,
        autoGenerated: false,
        generatedAt: null,
        generatedVersion: null,
      }));
  } catch {
    return [];
  }
}

export async function extractValueMetricsFromDocument(
  doc: { text?: string; name?: string },
  existingKpis: any[] = [],
): Promise<{ kpiActuals: any[]; agentRoiAttribution: string; benefitRealizationNotes: string }> {
  if (!doc?.text?.trim() || doc.text.trim().length < 200) {
    return { kpiActuals: [], agentRoiAttribution: "", benefitRealizationNotes: "" };
  }

  const system = `You are extracting value realization metrics from a business report or value assessment document. 
Extract: kpiActuals (array of {name, baseline, actual, unit, achievedPercent}), agentRoiAttribution (string summary of agent ROI), benefitRealizationNotes (string).
Return as JSON. Use null for fields not found. Do not invent numbers.`;

  const user = doc.text.slice(0, 4000);

  try {
    const raw = await callRegisteredRuntime(system, user, { max_tokens: 800 });
    const parsed = JSON.parse(String(raw || "").match(/\{[\s\S]*\}/)?.[0] || "{}");
    const priorNames = new Set(
      existingKpis.map((kpi: any) => String(typeof kpi === "string" ? kpi : kpi?.name || "").toLowerCase().trim()).filter(Boolean),
    );
    const deduped = Array.isArray(parsed.kpiActuals)
      ? parsed.kpiActuals.filter((kpi: any) => {
          const key = String(typeof kpi === "string" ? kpi : kpi?.name || "").toLowerCase().trim();
          return key && !priorNames.has(key);
        })
      : [];
    return {
      kpiActuals: deduped,
      agentRoiAttribution: parsed.agentRoiAttribution || "",
      benefitRealizationNotes: parsed.benefitRealizationNotes || "",
    };
  } catch {
    return { kpiActuals: [], agentRoiAttribution: "", benefitRealizationNotes: "" };
  }
}

export async function extractStrategyContextFromDocument(
  doc: { text?: string; name?: string },
  _existingContext: any = {},
): Promise<{ objectives: Array<{ text: string; confidenceScore: number }>; constraints: Array<{ text: string; confidenceScore: number }> }> {
  if (!doc?.text?.trim() || doc.text.trim().length < 200) {
    return { objectives: [], constraints: [] };
  }
  const system = `You are extracting strategy objectives and constraints from an executive transformation document.
Return JSON only in this shape:
{"objectives":[{"text":"","confidenceScore":0.0}],"constraints":[{"text":"","confidenceScore":0.0}]}
Only include explicitly stated items. Confidence scores must be between 0 and 1.`;
  try {
    const raw = await callRegisteredRuntime(system, doc.text.slice(0, 4500), { max_tokens: 900 });
    const parsed = JSON.parse(String(raw || "").match(/\{[\s\S]*\}/)?.[0] || "{}");
    return {
      objectives: Array.isArray(parsed.objectives) ? parsed.objectives.filter((item: any) => item?.text).map((item: any) => ({ text: String(item.text).trim(), confidenceScore: Number(item.confidenceScore || 0.6) })) : [],
      constraints: Array.isArray(parsed.constraints) ? parsed.constraints.filter((item: any) => item?.text).map((item: any) => ({ text: String(item.text).trim(), confidenceScore: Number(item.confidenceScore || 0.6) })) : [],
    };
  } catch {
    return { objectives: [], constraints: [] };
  }
}

export async function extractMobiliseContextFromDocument(
  doc: { text?: string; name?: string },
  _existingData: any = {},
): Promise<{ roles: Array<{ roleName: string; roleType: string; confidenceScore: number }> }> {
  if (!doc?.text?.trim() || doc.text.trim().length < 200) {
    return { roles: [] };
  }
  const system = `You are extracting delivery roles and team structure from a mobilisation or program-planning document.
Return JSON only in this shape:
{"roles":[{"roleName":"","roleType":"","confidenceScore":0.0}]}
Only include explicitly stated roles. Confidence scores must be between 0 and 1.`;
  try {
    const raw = await callRegisteredRuntime(system, doc.text.slice(0, 4500), { max_tokens: 900 });
    const parsed = JSON.parse(String(raw || "").match(/\{[\s\S]*\}/)?.[0] || "{}");
    return {
      roles: Array.isArray(parsed.roles)
        ? parsed.roles.filter((item: any) => item?.roleName || item?.roleType).map((item: any) => ({
            roleName: String(item.roleName || item.roleType || "").trim(),
            roleType: String(item.roleType || item.roleName || "").trim(),
            confidenceScore: Number(item.confidenceScore || 0.6),
          }))
        : [],
    };
  } catch {
    return { roles: [] };
  }
}

export async function extractBuildContextFromDocument(
  doc: { text?: string; name?: string },
  _existingData: any = {},
): Promise<{ testCases: Array<{ title: string; description: string; confidenceScore: number }> }> {
  if (!doc?.text?.trim() || doc.text.trim().length < 200) {
    return { testCases: [] };
  }
  const system = `You are extracting test plans and acceptance criteria from a build or engineering document.
Return JSON only in this shape:
{"testCases":[{"title":"","description":"","confidenceScore":0.0}]}
Only include explicitly stated test cases or acceptance checks. Confidence scores must be between 0 and 1.`;
  try {
    const raw = await callRegisteredRuntime(system, doc.text.slice(0, 4500), { max_tokens: 900 });
    const parsed = JSON.parse(String(raw || "").match(/\{[\s\S]*\}/)?.[0] || "{}");
    return {
      testCases: Array.isArray(parsed.testCases)
        ? parsed.testCases.filter((item: any) => item?.title || item?.description).map((item: any) => ({
            title: String(item.title || "Extracted test case").trim(),
            description: String(item.description || "").trim(),
            confidenceScore: Number(item.confidenceScore || 0.6),
          }))
        : [],
    };
  } catch {
    return { testCases: [] };
  }
}

export async function extractOperateContextFromDocument(
  doc: { text?: string; name?: string },
  _existingData: any = {},
): Promise<{ runbookItems: Array<{ title: string; detail: string; confidenceScore: number }> }> {
  if (!doc?.text?.trim() || doc.text.trim().length < 200) {
    return { runbookItems: [] };
  }
  const system = `You are extracting operational runbook items from an operations or support document.
Return JSON only in this shape:
{"runbookItems":[{"title":"","detail":"","confidenceScore":0.0}]}
Only include explicitly stated operational steps, alerts, or escalation items. Confidence scores must be between 0 and 1.`;
  try {
    const raw = await callRegisteredRuntime(system, doc.text.slice(0, 4500), { max_tokens: 900 });
    const parsed = JSON.parse(String(raw || "").match(/\{[\s\S]*\}/)?.[0] || "{}");
    return {
      runbookItems: Array.isArray(parsed.runbookItems)
        ? parsed.runbookItems.filter((item: any) => item?.title || item?.detail).map((item: any) => ({
            title: String(item.title || "Runbook item").trim(),
            detail: String(item.detail || "").trim(),
            confidenceScore: Number(item.confidenceScore || 0.6),
          }))
        : [],
    };
  } catch {
    return { runbookItems: [] };
  }
}

export async function extractGovernContextFromDocument(
  doc: { text: string; name: string; usableText: boolean },
  _existingGovern: Record<string, any> = {},
): Promise<{
  capturedRisks: string[];
  agentRegistryEntries: Array<{ agentName: string; missionStatement: string; autonomyLevel: string }>;
  complianceControlGaps: string[];
  hitlTriggers: string[];
}> {
  if (!doc?.usableText || !doc?.text?.trim()) {
    return { capturedRisks: [], agentRegistryEntries: [], complianceControlGaps: [], hitlTriggers: [] };
  }
  const system = `You are an AI governance analyst extracting governance artifacts from a document.
Return JSON only — no markdown, no explanation.
Shape: {
  "capturedRisks": ["risk descriptions — max 5"],
  "agentRegistryEntries": [{ "agentName": "...", "missionStatement": "...", "autonomyLevel": "supervised|semi-autonomous|autonomous" }],
  "complianceControlGaps": ["gap descriptions — max 4"],
  "hitlTriggers": ["trigger conditions — max 4"]
}
Only extract what is explicitly present. Return empty arrays if nothing found.`;
  const user = `Document: ${doc.name}\n\n${doc.text.slice(0, 4000)}`;
  try {
    const raw = await requestAIText(system, user, { max_tokens: 900 });
    const start = String(raw ?? "").indexOf("{");
    const end = String(raw ?? "").lastIndexOf("}");
    if (start === -1 || end === -1) {
      return { capturedRisks: [], agentRegistryEntries: [], complianceControlGaps: [], hitlTriggers: [] };
    }
    return JSON.parse(String(raw).slice(start, end + 1));
  } catch {
    return { capturedRisks: [], agentRegistryEntries: [], complianceControlGaps: [], hitlTriggers: [] };
  }
}

export async function extractOptimizeContextFromDocument(
  doc: { text: string; name: string; usableText: boolean },
  _existingOptimize: Record<string, any> = {},
): Promise<{
  learningObjects: Array<{ signal: string; hypothesis: string; owner: string }>;
  retrospectiveInsights: string[];
  performanceGaps: string[];
}> {
  if (!doc?.usableText || !doc?.text?.trim()) {
    return { learningObjects: [], retrospectiveInsights: [], performanceGaps: [] };
  }
  const system = `You are an AI program optimization analyst extracting learning cycle artifacts from a document.
Return JSON only — no markdown, no explanation.
Shape: {
  "learningObjects": [{ "signal": "...", "hypothesis": "...", "owner": "..." }],
  "retrospectiveInsights": ["insight descriptions — max 5"],
  "performanceGaps": ["gap descriptions — max 4"]
}
Only extract explicitly present content. Return empty arrays if nothing found.`;
  const user = `Document: ${doc.name}\n\n${doc.text.slice(0, 4000)}`;
  try {
    const raw = await requestAIText(system, user, { max_tokens: 800 });
    const start = String(raw ?? "").indexOf("{");
    const end = String(raw ?? "").lastIndexOf("}");
    if (start === -1 || end === -1) {
      return { learningObjects: [], retrospectiveInsights: [], performanceGaps: [] };
    }
    return JSON.parse(String(raw).slice(start, end + 1));
  } catch {
    return { learningObjects: [], retrospectiveInsights: [], performanceGaps: [] };
  }
}
