/**
 * A DOCUMENT THAT DID NOT EARN ITS CONFIDENCE MUST NOT LOOK LIKE ONE THAT DID.
 *
 * The provisional ontology is generated by an ensemble: the same grounded prompt
 * is run `ONTOLOGY_VOTE_N` times and the drafts are reconciled by majority vote.
 * The reconciliation is the point — the LLM stays the author, only the agreement
 * is code, so the same drafts always yield the same document and a borderline
 * concept has to flip a whole vote to change it. The vote share is described in
 * that code as "a real confidence signal": a concept that misses consensus rides
 * into gaps as an interview question instead of being asserted.
 *
 * THE DEFECT. Every draft call carries `.catch(() => null)`, and when fewer than
 * the threshold come back the voted path returns null and the caller falls
 * through to ONE ordinary generation. That fallback is correct — a programme
 * should not be blocked because an API flaked. What was wrong is that it was
 * SILENT. The resulting document is a single draft with no vote, no agreement
 * bar and no confidence signal, and nothing anywhere said so. It is
 * indistinguishable from a reconciled one, which makes it worse than a failure:
 * a failure gets retried, and this gets trusted.
 *
 * NOT A GAP, DELIBERATELY. Gaps drive the movement gate (`gaps === 0` is part of
 * `done`) and become interview questions. "Two of five drafts timed out" is
 * neither — nobody can answer it, and routing it there would hold a programme
 * on an API's bad afternoon. It is PROVENANCE: a stamp on the document saying
 * how the document was made, carried wherever the document goes.
 */

/** What actually happened when the ensemble ran. */
export interface OntologyVoteOutcome {
  /** How many drafts were requested — `ONTOLOGY_VOTE_N`. */
  asked: number;
  /** How many came back parseable, with a non-empty entity list. */
  usable: number;
  /** The agreement bar a concept had to clear — `ONTOLOGY_VOTE_THRESHOLD`. */
  threshold: number;
}

/** How a stored ontology says it was made. */
export interface OntologyReconciliation {
  /** "voted" — reconciled from drafts. "single-draft" — the fallback ran. */
  method: "voted" | "single-draft";
  asked: number;
  usable: number;
  threshold: number;
  /** Plain-language provenance, written for whoever opens the document. */
  note: string;
}

const clamp = (n: unknown, lo: number, hi: number): number => {
  const v = Math.floor(Number(n));
  return Number.isFinite(v) ? Math.min(hi, Math.max(lo, v)) : lo;
};

/**
 * Stamp the outcome.
 *
 * The wording carries the CONSEQUENCE, not just the count, because the count
 * alone means nothing to the person reading the document six weeks later. What
 * they need to know is whether a concept in here cleared a bar or was simply
 * asserted once.
 *
 * A short-handed vote is reported too, and it is worth being precise about which
 * way it cuts: the threshold is ABSOLUTE, so 3-of-4 is a stricter bar than
 * 3-of-5. Losing a draft does not weaken the document — it narrows it, and more
 * concepts fall through to interview questions than usual. Saying so stops
 * somebody re-running the agent to "fix" a gap list that is behaving correctly.
 */
export function reconciliationOf(outcome: OntologyVoteOutcome): OntologyReconciliation {
  const asked = clamp(outcome.asked, 0, 99);
  const threshold = clamp(outcome.threshold, 0, 99);
  const usable = clamp(outcome.usable, 0, asked);
  if (usable < threshold || threshold === 0) {
    return {
      method: "single-draft", asked, usable, threshold,
      note: `Not reconciled. ${usable} of ${asked} drafts came back and ${threshold} were needed to vote, so this document is a SINGLE generation: no concept in it cleared an agreement bar, and the vote share that normally routes a borderline concept to an interview question is absent. Treat every assertion as one model's reading. Re-running the agent is the fix.`,
    };
  }
  return {
    method: "voted", asked, usable, threshold,
    note: usable < asked
      ? `Reconciled from ${usable} of ${asked} drafts — ${asked - usable} did not come back. The bar is absolute, so ${threshold} of ${usable} is a STRICTER majority than ${threshold} of ${asked}: expect fewer asserted concepts and a longer interview list than a full run. That is the vote behaving correctly, not a fault to re-run.`
      : `Reconciled by majority vote from all ${asked} drafts; ${threshold} had to agree before a concept was asserted, and anything short of that rode into gaps as an interview question.`,
  };
}

/** Whether a stored document was reconciled. Absent stamp → unknown, so this
 * answers false only when the document SAYS it was a single draft: a document
 * generated before this existed must not be reported as degraded. */
export function wasReconciled(doc: unknown): boolean | null {
  if (typeof doc !== "object" || doc === null) return null;
  const r = (doc as Record<string, unknown>).reconciliation;
  if (typeof r !== "object" || r === null) return null;
  const method = (r as Record<string, unknown>).method;
  return method === "voted" ? true : method === "single-draft" ? false : null;
}
