/**
 * Artifact Map — the complete programme artifact tree, organised by phase.
 *
 * For every phase the programme runs, this renders a collapsible branch that
 * gathers the three things the methodology binds to that phase:
 *   • Inputs    — the phase input schema fields and whether each is provided.
 *   • Artifacts — the required (and any extra) artifacts, their state and quality.
 *   • Source    — a plain-English provenance summary (how the artifacts were
 *                 produced and how much input context the phase has).
 *
 * It is a pure selector over normalised programme data (artifactModel +
 * phaseInputSchema), so it stays deterministic and needs no backend.
 */
import React from "react";
import type { ProgramSummary } from "@/new/types";
import { buildArtifactModel, type ArtifactNode } from "@/v3/lib/artifactModel";
import { getPhaseInputSchema, type PhaseInputField } from "@/v3/lib/phaseInputSchema";

type Tone = "good" | "warning" | "muted";

const TONE_COLOR: Record<Tone, string> = {
  good: "var(--v3-green)",
  warning: "var(--v3-amber)",
  muted: "var(--v3-text-muted)",
};

/** Read the persisted phase inputs map, tolerating both rawData shapes. */
function readPhaseInputs(program: ProgramSummary, phaseId: string): Record<string, unknown> {
  const raw = (program.rawData ?? {}) as Record<string, unknown>;
  const source = typeof raw.data === "object" && raw.data !== null
    ? (raw.data as Record<string, unknown>)
    : raw;
  const phaseInputs = typeof source.phaseInputs === "object" && source.phaseInputs !== null
    ? (source.phaseInputs as Record<string, Record<string, unknown>>)
    : {};
  return phaseInputs[phaseId] ?? {};
}

function valuePreview(value: unknown): string | null {
  if (value == null) return null;
  const text = typeof value === "string" ? value.trim() : String(value);
  if (!text) return null;
  return text.length > 120 ? `${text.slice(0, 117)}…` : text;
}

function artifactTone(node: ArtifactNode): Tone {
  if (!node.present) return node.required ? "warning" : "muted";
  if (node.state === "approved" || node.state === "ready") return "good";
  return "warning";
}

function artifactStatusLabel(node: ArtifactNode): string {
  if (!node.present) return node.required ? "Missing" : "Optional";
  return node.state.charAt(0).toUpperCase() + node.state.slice(1);
}

/** Provenance one-liners for a phase: how its present artifacts were sourced. */
function sourceSummary(
  artifacts: ArtifactNode[],
  inputsFilled: number,
  inputsTotal: number,
): string[] {
  const present = artifacts.filter((a) => a.present);
  const generated = present.filter((a) => a.origin === "generated").length;
  const uploaded = present.filter((a) => a.origin === "uploaded").length;
  const lines: string[] = [];

  if (present.length === 0) {
    lines.push("No artifacts produced yet — generate from this phase's inputs.");
  } else {
    const parts: string[] = [];
    if (generated > 0) parts.push(`${generated} generated by ATOS`);
    if (uploaded > 0) parts.push(`${uploaded} uploaded by the team`);
    lines.push(`${present.length} artifact${present.length === 1 ? "" : "s"} on record — ${parts.join(", ")}.`);
  }

  if (inputsTotal > 0) {
    lines.push(
      inputsFilled === inputsTotal
        ? `All ${inputsTotal} input${inputsTotal === 1 ? "" : "s"} provided as source context.`
        : `${inputsFilled} of ${inputsTotal} inputs provided as source context.`,
    );
  }

  return lines;
}

function Dot({ tone }: { tone: Tone }) {
  return <span className="v3-amap-dot" style={{ background: TONE_COLOR[tone] }} />;
}

function Caret({ open }: { open: boolean }) {
  return <span className="v3-amap-caret">{open ? "▾" : "▸"}</span>;
}

interface GroupProps {
  groupKey: string;
  title: string;
  count: string;
  expanded: Set<string>;
  onToggle: (key: string) => void;
  children: React.ReactNode;
  empty?: boolean;
}

function Group({ groupKey, title, count, expanded, onToggle, children, empty }: GroupProps) {
  const open = expanded.has(groupKey);
  return (
    <div className="v3-amap-group">
      <button
        type="button"
        className="v3-amap-grouphead"
        onClick={() => !empty && onToggle(groupKey)}
        disabled={empty}
      >
        {empty ? <span className="v3-amap-caret is-leaf">•</span> : <Caret open={open} />}
        <span className="v3-amap-group-title">{title}</span>
        <span className="v3-amap-count">{count}</span>
      </button>
      {open && !empty ? <div className="v3-amap-children">{children}</div> : null}
    </div>
  );
}

export function ArtifactMapTree({ program }: { program: ProgramSummary | null }) {
  const model = React.useMemo(() => buildArtifactModel(program), [program]);

  const phaseData = React.useMemo(() => {
    if (!program) return [];
    return model.phases.map((phase) => {
      const fields: PhaseInputField[] = getPhaseInputSchema(phase.phaseId).fields;
      const values = readPhaseInputs(program, phase.phaseId);
      const inputs = fields.map((field) => {
        const preview = valuePreview(values[field.id]);
        return { field, preview, filled: preview != null };
      });
      const inputsFilled = inputs.filter((i) => i.filled).length;
      return {
        phase,
        inputs,
        inputsFilled,
        inputsTotal: fields.length,
        source: sourceSummary(phase.artifacts, inputsFilled, fields.length),
      };
    });
  }, [program, model.phases]);

  // Default: every phase branch open, its sub-groups closed — scannable overview.
  const allPhaseKeys = React.useMemo(
    () => phaseData.map((p) => `phase:${p.phase.phaseId}`),
    [phaseData],
  );
  const [expanded, setExpanded] = React.useState<Set<string>>(() => new Set());

  React.useEffect(() => {
    setExpanded(new Set(allPhaseKeys));
  }, [allPhaseKeys]);

  const toggle = React.useCallback((key: string) => {
    setExpanded((current) => {
      const next = new Set(current);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }, []);

  const allKeys = React.useMemo(() => {
    const keys: string[] = [];
    for (const p of phaseData) {
      const id = p.phase.phaseId;
      keys.push(`phase:${id}`, `inputs:${id}`, `artifacts:${id}`, `source:${id}`);
    }
    return keys;
  }, [phaseData]);

  if (!program || phaseData.length === 0) {
    return <div className="v3-context-artifacts-empty">No artifact tree for this programme yet.</div>;
  }

  return (
    <div className="v3-amap">
      <div className="v3-amap-toolbar">
        <span className="v3-amap-totals">
          <strong>{model.totals.present}</strong> of <strong>{model.totals.required}</strong> required artifacts present
          {model.totals.avgQuality != null ? <> · <strong>{model.totals.avgQuality}%</strong> avg quality</> : null}
          {" "}across <strong>{phaseData.length}</strong> phases
        </span>
        <div className="v3-amap-toolbar-actions">
          <button type="button" className="v3-button ghost" onClick={() => setExpanded(new Set(allKeys))}>
            Expand all
          </button>
          <button type="button" className="v3-button ghost" onClick={() => setExpanded(new Set())}>
            Collapse all
          </button>
        </div>
      </div>

      <div className="v3-amap-tree">
        {phaseData.map(({ phase, inputs, inputsFilled, inputsTotal, source }) => {
          const phaseKey = `phase:${phase.phaseId}`;
          const phaseOpen = expanded.has(phaseKey);
          const phaseTone: Tone = phase.missing === 0 ? "good" : phase.present > 0 ? "warning" : "muted";
          return (
            <div key={phase.phaseId} className="v3-amap-phase">
              <button type="button" className="v3-amap-phasehead" onClick={() => toggle(phaseKey)}>
                <Caret open={phaseOpen} />
                <Dot tone={phaseTone} />
                <span className="v3-amap-phase-name">{phase.phaseLabel}</span>
                <span className="v3-amap-phase-meta">
                  <span className="v3-amap-pill">{phase.present}/{phase.required} artifacts</span>
                  {inputsTotal > 0 ? (
                    <span className="v3-amap-pill">{inputsFilled}/{inputsTotal} inputs</span>
                  ) : null}
                  {phase.avgQuality != null ? (
                    <span className="v3-amap-pill subtle">{phase.avgQuality}% quality</span>
                  ) : null}
                </span>
              </button>

              {phaseOpen ? (
                <div className="v3-amap-phasebody">
                  {/* Inputs */}
                  <Group
                    groupKey={`inputs:${phase.phaseId}`}
                    title="Inputs"
                    count={inputsTotal > 0 ? `${inputsFilled}/${inputsTotal} provided` : "none"}
                    expanded={expanded}
                    onToggle={toggle}
                    empty={inputsTotal === 0}
                  >
                    {inputs.map(({ field, preview, filled }) => (
                      <div key={field.id} className="v3-amap-leaf">
                        <Dot tone={filled ? "good" : field.required ? "warning" : "muted"} />
                        <div className="v3-amap-leaf-body">
                          <div className="v3-amap-leaf-top">
                            <span className="v3-amap-leaf-label">{field.label}</span>
                            {field.required ? <span className="v3-amap-tag req">Required</span> : null}
                            {!filled ? <span className="v3-amap-tag muted">Not provided</span> : null}
                          </div>
                          {preview ? (
                            <p className="v3-amap-leaf-source">{preview}</p>
                          ) : field.hint ? (
                            <p className="v3-amap-leaf-source subtle">{field.hint}</p>
                          ) : null}
                        </div>
                      </div>
                    ))}
                  </Group>

                  {/* Artifacts */}
                  <Group
                    groupKey={`artifacts:${phase.phaseId}`}
                    title="Artifacts"
                    count={`${phase.present}/${phase.required} present`}
                    expanded={expanded}
                    onToggle={toggle}
                    empty={phase.artifacts.length === 0}
                  >
                    {phase.artifacts.map((node) => {
                      const tone = artifactTone(node);
                      return (
                        <div key={node.key} className="v3-amap-leaf">
                          <Dot tone={tone} />
                          <div className="v3-amap-leaf-body">
                            <div className="v3-amap-leaf-top">
                              <span className="v3-amap-leaf-label">{node.label}</span>
                              <span className="v3-amap-tag" style={{ color: TONE_COLOR[tone] }}>
                                {artifactStatusLabel(node)}
                              </span>
                              {!node.required ? <span className="v3-amap-tag muted">Extra</span> : null}
                              {node.quality != null ? (
                                <span className="v3-amap-tag subtle">{node.quality}%</span>
                              ) : null}
                            </div>
                            {node.evidence ? (
                              <p className="v3-amap-leaf-source">{node.evidence}</p>
                            ) : !node.present ? (
                              <p className="v3-amap-leaf-source subtle">Not yet produced for this phase.</p>
                            ) : null}
                          </div>
                        </div>
                      );
                    })}
                  </Group>

                  {/* Source summary */}
                  <Group
                    groupKey={`source:${phase.phaseId}`}
                    title="Source summary"
                    count={`${phase.present + inputsFilled} signals`}
                    expanded={expanded}
                    onToggle={toggle}
                  >
                    {source.map((line, i) => (
                      <div key={i} className="v3-amap-leaf">
                        <Dot tone="muted" />
                        <div className="v3-amap-leaf-body">
                          <p className="v3-amap-leaf-source">{line}</p>
                        </div>
                      </div>
                    ))}
                  </Group>
                </div>
              ) : null}
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default ArtifactMapTree;
