/**
 * documentExport — client-side export utilities for AI-generated documents.
 * Uses browser print API for PDF and Office-compatible HTML for DOCX.
 * No external dependencies required.
 */

/** Export content as PDF via browser print dialog (user can save as PDF) */
export function exportAsPDF(title: string, htmlContent: string): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #1a1a2e; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 20pt; font-weight: 700; color: #1a1a2e; margin-bottom: 8px; }
    h2 { font-size: 14pt; font-weight: 600; color: #2d2d5e; margin-top: 24px; margin-bottom: 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    h3 { font-size: 11pt; font-weight: 600; color: #374151; margin-top: 16px; margin-bottom: 4px; }
    p { margin-bottom: 10px; }
    ul { margin: 8px 0 12px 20px; }
    li { margin-bottom: 4px; }
    .meta { font-size: 9pt; color: #6b7280; margin-bottom: 24px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 9pt; font-weight: 500; }
    .badge-green { background: #dcfce7; color: #166534; }
    .badge-amber { background: #fef3c7; color: #92400e; }
    .badge-red { background: #fee2e2; color: #991b1b; }
    .slide { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px; page-break-inside: avoid; }
    .slide-number { font-size: 9pt; color: #9ca3af; margin-bottom: 4px; }
    .section { margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { background: #f3f4f6; text-align: left; padding: 8px; font-size: 9pt; border: 1px solid #e5e7eb; }
    td { padding: 8px; font-size: 9pt; border: 1px solid #e5e7eb; vertical-align: top; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 8pt; color: #9ca3af; }
    @media print {
      body { padding: 20px; }
      .slide { page-break-inside: avoid; }
      h2 { page-break-after: avoid; }
    }
  </style>
</head>
<body>
${htmlContent}
<div class="footer">Generated by ATOS · Brillio · ${new Date().toLocaleDateString()}</div>
</body>
</html>`);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 500);
}

/** Export content as Word-compatible HTML (.doc download) */
export function exportAsDocx(title: string, htmlContent: string): void {
  const wordHtml = `<html xmlns:o='urn:schemas-microsoft-com:office:office'
xmlns:w='urn:schemas-microsoft-com:office:word'
xmlns='http://www.w3.org/TR/REC-html40'>
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<!--[if gte mso 9]>
<xml><w:WordDocument><w:View>Print</w:View><w:Zoom>90</w:Zoom></w:WordDocument></xml>
<![endif]-->
<style>
  body { font-family: 'Calibri', Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #1a1a2e; }
  h1 { font-size: 18pt; font-weight: bold; color: #1a1a2e; }
  h2 { font-size: 14pt; font-weight: bold; color: #2d2d5e; border-bottom: 1pt solid #e5e7eb; padding-bottom: 4pt; margin-top: 18pt; }
  h3 { font-size: 11pt; font-weight: bold; color: #374151; margin-top: 12pt; }
  ul { margin-left: 20pt; }
  li { margin-bottom: 4pt; }
  p { margin-bottom: 8pt; }
  table { border-collapse: collapse; width: 100%; }
  th { background: #f3f4f6; padding: 6pt; border: 1pt solid #d1d5db; font-weight: bold; }
  td { padding: 6pt; border: 1pt solid #d1d5db; }
</style>
</head>
<body>
${htmlContent}
<p style="font-size:8pt;color:#9ca3af;margin-top:30pt;border-top:1pt solid #e5e7eb;padding-top:8pt">Generated by ATOS · Brillio · ${new Date().toLocaleDateString()}</p>
</body>
</html>`;

  const blob = new Blob([wordHtml], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

/** Export plain text */
export function exportAsText(title: string, content: string): void {
  const blob = new Blob([`${title}\n${"=".repeat(title.length)}\n\n${content}\n\nGenerated by ATOS · Brillio · ${new Date().toLocaleDateString()}`], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// ── Document-specific HTML builders ──────────────────────────────────────────

export function narrativeToHtml(program: { name?: string; client?: string }, narrative: string, confidence: number, generatedAt: string): string {
  const confLabel = confidence >= 0.8 ? "High confidence" : confidence >= 0.6 ? "Medium confidence" : "Low confidence";
  return `
<h1>Programme Narrative</h1>
<p class="meta">${program.name || "Programme"} ${program.client ? `· ${program.client}` : ""} · Generated ${new Date(generatedAt).toLocaleDateString()}</p>
<div class="section">
  <p>${escapeHtml(narrative)}</p>
</div>
<p class="meta">Confidence: ${confLabel} (${Math.round(confidence * 100)}%)</p>`;
}

export function deckToHtml(program: { name?: string; client?: string }, deck: { title?: string; audience?: string; slides?: Array<{ slideNumber?: number; title?: string; type?: string; talkingPoints?: string[]; dataCallouts?: string[]; recommendedVisual?: string | null; speakerNotes?: string }>; programHealthSummary?: string }): string {
  const slides = Array.isArray(deck.slides) ? deck.slides : [];
  const slidesHtml = slides.map((slide) => `
<div class="slide">
  <div class="slide-number">Slide ${slide.slideNumber || ""} · ${(slide.type || "").replace(/-/g, " ").toUpperCase()}</div>
  <h2>${escapeHtml(slide.title || "")}</h2>
  ${slide.talkingPoints?.length ? `<ul>${slide.talkingPoints.map((p) => `<li>${escapeHtml(p)}</li>`).join("")}</ul>` : ""}
  ${slide.dataCallouts?.length ? `<p><strong>Key data:</strong> ${slide.dataCallouts.map(escapeHtml).join(" · ")}</p>` : ""}
  ${slide.recommendedVisual ? `<p><em>Visual: ${escapeHtml(slide.recommendedVisual)}</em></p>` : ""}
  ${slide.speakerNotes ? `<p style="color:#6b7280;font-size:9.5pt"><strong>Speaker notes:</strong> ${escapeHtml(slide.speakerNotes)}</p>` : ""}
</div>`).join("\n");

  return `
<h1>${escapeHtml(deck.title || "Executive Deck")}</h1>
<p class="meta">${program.name || "Programme"} ${program.client ? `· ${program.client}` : ""} · Audience: ${deck.audience || "Executive"}</p>
${deck.programHealthSummary ? `<p>${escapeHtml(deck.programHealthSummary)}</p>` : ""}
${slidesHtml}`;
}

export function planToHtml(program: { name?: string; client?: string }, plan: { milestones?: Array<Record<string, unknown>>; nextThreeActions?: Array<Record<string, unknown>>; blockerSummary?: Array<Record<string, unknown>>; criticalPath?: string[] }): string {
  const milestones = Array.isArray(plan.milestones) ? plan.milestones : [];
  const actions = Array.isArray(plan.nextThreeActions) ? plan.nextThreeActions : [];
  const blockers = Array.isArray(plan.blockerSummary) ? plan.blockerSummary : [];

  const milestonesHtml = milestones.length ? `
<h2>Milestones</h2>
<table>
  <tr><th>Milestone</th><th>Phase</th><th>Due Date</th><th>Status</th><th>Owner</th></tr>
  ${milestones.map((m) => `<tr><td>${escapeHtml(String(m.title || ""))}</td><td>${escapeHtml(String(m.phase || ""))}</td><td>${escapeHtml(String(m.dueDate || "TBD"))}</td><td>${escapeHtml(String(m.status || ""))}</td><td>${escapeHtml(String(m.owner || "—"))}</td></tr>`).join("")}
</table>` : "";

  const actionsHtml = actions.length ? `
<h2>Next Actions</h2>
<ul>${actions.map((a) => `<li><strong>${escapeHtml(String(a.action || ""))}</strong> — ${escapeHtml(String(a.owner || "TBC"))} (${escapeHtml(String(a.phase || ""))})<br><em>${escapeHtml(String(a.rationale || ""))}</em></li>`).join("")}</ul>` : "";

  const blockersHtml = blockers.length ? `
<h2>Blockers</h2>
<ul>${blockers.map((b) => `<li>[${String(b.severity || "").toUpperCase()}] ${escapeHtml(String(b.blocker || ""))} — <em>${escapeHtml(String(b.resolution || ""))}</em></li>`).join("")}</ul>` : "";

  return `
<h1>Programme Plan</h1>
<p class="meta">${program.name || "Programme"} ${program.client ? `· ${program.client}` : ""}</p>
${plan.criticalPath?.length ? `<p><strong>Critical Path:</strong> ${plan.criticalPath.join(" → ")}</p>` : ""}
${milestonesHtml}
${actionsHtml}
${blockersHtml}`;
}
