/**
 * Formal (document-style) artifacts are generated by the run-agent edge function
 * and stored as structured JSON objects at the TOP LEVEL of program data, under a
 * dedicated field key — not as a string inside phaseArtifacts[phase][id].content
 * (that entry is only a status stub). This module maps each producing-agent id to
 * its field key and renders the structured object into readable preview text, so
 * the StageView artifact rows can show the real draft body.
 *
 * Keep FORMAL_ARTIFACT_FIELD_KEYS in sync with FORMAL_ARTIFACT_AGENTS in
 * supabase/functions/run-agent/index.ts.
 */

export const FORMAL_ARTIFACT_FIELD_KEYS: Record<string, string> = {
  "charter": "transformationCharter",
  "business-case": "businessCaseDoc",
  "outcome-framework": "outcomeFramework",
  "strategic-roadmap": "strategicRoadmap",
  "governance-model": "governanceModel",
  "raci-matrix": "raciMatrix",
  "requirements-catalog": "requirementsCatalog",
  "future-state-design": "futureStateDesign",
  "target-operating-model": "targetOperatingModel",
  "solution-architecture": "solutionArchitecture",
  "test-plan": "testPlan",
  "runbook": "runbook",
  "support-model": "supportModel",
  "optimization-backlog": "optimizationBacklog",
};

// Provenance/scoring fields that are not part of the readable document body.
const SKIP_KEYS = new Set(["confidence", "generatedat", "title"]);

function isSkippable(key: string): boolean {
  const k = key.toLowerCase();
  return SKIP_KEYS.has(k) || k.startsWith("_");
}

function humanize(key: string): string {
  const spaced = key
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function primitive(value: unknown): string {
  return typeof value === "string" ? value.trim() : String(value);
}

function isObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

// Field names that make the best bullet header for an object, in priority order.
const LEAD_KEYS = ["outcome", "name", "title", "benefit", "category", "phase", "role", "area", "item", "requirement", "control", "step", "risk"];

const INDENT = "  ";

/** Inline an object's primitive fields as "**Label:** value, …". */
function inlineObject(obj: Record<string, unknown>): string {
  return Object.entries(obj)
    .filter(([k, v]) => !isSkippable(k) && v !== null && v !== undefined && v !== "" && typeof v !== "object")
    .map(([k, v]) => `**${humanize(k)}:** ${primitive(v)}`)
    .join(", ");
}

/** Render one object as a markdown bullet group; a meaningful field leads. */
function renderObjectAsBullet(obj: Record<string, unknown>, depth: number): string[] {
  const pad = INDENT.repeat(depth);
  const sub = INDENT.repeat(depth + 1);
  const entries = Object.entries(obj).filter(([k, v]) => !isSkippable(k) && v !== null && v !== undefined && v !== "");
  const lead = entries.find(([k, v]) => LEAD_KEYS.includes(k.toLowerCase()) && typeof v === "string" && v.trim())
    ?? entries.find(([, v]) => typeof v === "string" && v.trim());
  const lines: string[] = [`${pad}- ${lead ? primitive(lead[1]) : ""}`.trimEnd()];
  for (const [k, v] of entries) {
    if (lead && k === lead[0]) continue;
    if (Array.isArray(v)) {
      const prims = v.filter((x) => x !== null && x !== undefined && typeof x !== "object").map(primitive).filter(Boolean);
      if (prims.length) lines.push(`${sub}- **${humanize(k)}:** ${prims.join(", ")}`);
      for (const o of v.filter(isObject)) {
        const kv = inlineObject(o);
        if (kv) lines.push(`${sub}- **${humanize(k)}** — ${kv}`);
      }
    } else if (isObject(v)) {
      const kv = inlineObject(v);
      if (kv) lines.push(`${sub}- **${humanize(k)}:** ${kv}`);
    } else {
      const s = primitive(v);
      if (s) lines.push(`${sub}- **${humanize(k)}:** ${s}`);
    }
  }
  return lines;
}

/** Render a nested object's fields as subheaders / "Label: value" / bullets. */
function renderObjectLines(obj: Record<string, unknown>, depth: number): string[] {
  const pad = INDENT.repeat(depth);
  const lines: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    if (isSkippable(k) || v === null || v === undefined || v === "") continue;
    if (Array.isArray(v)) {
      const items = v.filter((x) => x !== null && x !== undefined);
      if (!items.length) continue;
      lines.push(`${pad}### ${humanize(k)}`);
      for (const it of items) {
        if (isObject(it)) lines.push(...renderObjectAsBullet(it, depth));
        else if (typeof it !== "object") { const s = primitive(it); if (s) lines.push(`${pad}- ${s}`); }
      }
    } else if (isObject(v)) {
      const sub = renderObjectLines(v, depth + 1);
      if (sub.length) { lines.push(`${pad}### ${humanize(k)}`); lines.push(...sub); }
    } else {
      const s = primitive(v);
      if (s) lines.push(`${pad}**${humanize(k)}:** ${s}`);
    }
  }
  return lines;
}

/**
 * Turn a structured formal-artifact object into markdown-lite text. Top-level
 * keys become "## " section headings; nested keys "### "; arrays become "- "
 * bullets (indented by two spaces per depth); "**Label:**" marks inline labels.
 * Blocks are blank-line separated so the renderer can stagger them. Returns ""
 * when there is nothing renderable.
 */
export function formatStructuredDoc(value: unknown): string {
  if (typeof value === "string") return value.trim();
  if (!isObject(value)) return "";

  const blocks: string[] = [];
  for (const [k, v] of Object.entries(value)) {
    if (isSkippable(k) || v === null || v === undefined || v === "") continue;
    const heading = `## ${humanize(k)}`;
    if (Array.isArray(v)) {
      const items = v.filter((x) => x !== null && x !== undefined);
      if (!items.length) continue;
      const lines: string[] = [];
      for (const it of items) {
        if (isObject(it)) lines.push(...renderObjectAsBullet(it, 0));
        else if (typeof it !== "object") { const s = primitive(it); if (s) lines.push(`- ${s}`); }
      }
      if (lines.length) blocks.push(`${heading}\n${lines.join("\n")}`);
    } else if (isObject(v)) {
      const lines = renderObjectLines(v, 0);
      if (lines.length) blocks.push(`${heading}\n${lines.join("\n")}`);
    } else {
      const s = primitive(v);
      if (s) blocks.push(`${heading}\n${s}`);
    }
  }
  return blocks.join("\n\n");
}

/**
 * Resolve the readable draft body for a formal artifact id from program data
 * (the data root that also holds phaseArtifacts/phaseInputs). Returns null when
 * the artifact is not a formal document or has no stored content.
 */
export function getFormalArtifactContent(source: Record<string, unknown> | null, artifactId: string): string | null {
  if (!source) return null;
  const fieldKey = FORMAL_ARTIFACT_FIELD_KEYS[artifactId];
  if (!fieldKey) return null;
  const text = formatStructuredDoc(source[fieldKey]);
  return text.trim() ? text : null;
}

/**
 * The AI's self-assessed confidence for a formal document, read from the same
 * top-level mirror as its body. run-agent returns `confidence` (0-1) on the
 * generation result and stores it on the mirror object, but NOT on the
 * phaseArtifacts ledger record — so without this, a formal-document card has no
 * quality signal to show until the independent review lands. Returns a 0-100
 * score, or null when the artifact is not a formal document / has no confidence.
 */
export function getFormalArtifactConfidence(source: Record<string, unknown> | null, artifactId: string): number | null {
  if (!source) return null;
  const fieldKey = FORMAL_ARTIFACT_FIELD_KEYS[artifactId];
  if (!fieldKey) return null;
  const doc = source[fieldKey];
  if (!isObject(doc)) return null;
  const confidence = doc.confidence;
  if (typeof confidence !== "number" || !Number.isFinite(confidence)) return null;
  return Math.round(confidence <= 1 ? confidence * 100 : confidence);
}
