/**
 * The artifact studio — the drill-down for every generated document, opened
 * from any card or Library row. Each artifact type renders its own WYSIWYG
 * editor (the ontology is a graph, the atlas a heatmap and step tables, the
 * charter structured prose); edits merge back into the generator's own shape
 * and land on the attestation trail. A typeset document view stays one tap
 * away, and artifacts with no stored structure fall back to it.
 */
import React, { useEffect, useMemo, useState } from "react";
import type { ProgramSummary } from "@/new/types";
import { artifactDocument, type ArtifactCardModel } from "@/v3/components/flow/flowShellData";
import { groundingFor, citationGraph, resourceUri, artifactFabioType, SEMANTIC_CONTEXT } from "@/v3/components/flow/flowSemantics";
import { readArtifactDoc } from "@/v3/components/flow/flowArtifactEdit";
import { STUDIO_REGISTRY } from "./studios";

/** Artifacts consumed linearly by stakeholders — the document IS the deliverable. */
const DOC_FIRST = new Set(["charter", "runbook"]);

export interface ArtifactEditInput {
  fieldKey: string;
  movementId: string;
  title: string;
  doc: Record<string, unknown>;
}

export default function FlowArtifactStudio({ program, artifact, onClose, onRegenerate, onSaveDoc }: {
  program: ProgramSummary;
  artifact: ArtifactCardModel;
  onClose: () => void;
  onRegenerate?: () => void;
  onSaveDoc?: (input: ArtifactEditInput) => Promise<void>;
}) {
  const entry = STUDIO_REGISTRY[artifact.id];
  const storedDoc = useMemo(
    () => (entry ? readArtifactDoc(program, entry.fieldKey) : null),
    [program, entry],
  );

  const [draft, setDraft] = useState<Record<string, unknown> | null>(storedDoc);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [savedTick, setSavedTick] = useState(false);
  // Read-and-share artifacts open as the typeset document — the deliverable
  // form — with the studio one tap away; operated artifacts open editing.
  const [asDocument, setAsDocument] = useState(() => DOC_FIRST.has(artifact.id));

  // A regenerate or portal write can refresh the programme under the open
  // studio — follow the store while the user hasn't started editing.
  useEffect(() => {
    if (!dirty) setDraft(storedDoc);
  }, [storedDoc, dirty]);

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const canEdit = !!entry && !!draft && !!onSaveDoc;
  const studioActive = canEdit && !asDocument;

  const save = async () => {
    if (!entry || !draft || !onSaveDoc) return;
    setSaving(true);
    try {
      await onSaveDoc({ fieldKey: entry.fieldKey, movementId: artifact.movementId, title: artifact.title, doc: draft });
      setDirty(false);
      setSavedTick(true);
      window.setTimeout(() => setSavedTick(false), 2200);
    } finally {
      setSaving(false);
    }
  };

  const body = artifactDocument(program, artifact.id);
  const blocks = useMemo(() => (body ?? "")
    .replace(/\*\*/g, "")
    .split(/\n{2,}/)
    .map((block) => block.trimEnd())
    .filter(Boolean)
    .map((block) => block.split("\n").map((line) => {
      const heading = line.match(/^#{1,4}\s+(.*)$/);
      if (heading) return { kind: "h" as const, text: heading[1] };
      const bullet = line.match(/^\s*[-•]\s+(.*)$/);
      if (bullet) return { kind: "li" as const, text: bullet[1] };
      return { kind: "p" as const, text: line };
    })), [body]);

  const grounding = useMemo(() => groundingFor(program, artifact.id, artifact.movementId), [program, artifact]);
  const edited = draft && typeof draft.editedAt === "string" ? String(draft.editedAt).slice(0, 10) : null;

  return (
    <>
      <div className="v3fs-doc-backdrop" onClick={onClose} aria-hidden="true" />
      <div className={`v3fs-docview${studioActive ? " v3fs-studio" : ""}`} role="dialog" aria-modal="true" aria-label={artifact.title}>
        <header className="v3fs-docview-h">
          <div>
            <h2>{artifact.title}</h2>
            <span className="v3fs-docview-m">
              {[artifact.confidence != null ? `confidence ${artifact.confidence}%` : null,
                artifact.stale ? "evidence changed since generation" : null,
                edited ? `hand-edited ${edited}` : null]
                .filter(Boolean).join(" · ") || "generated by ATOS"}
            </span>
          </div>
          <div className="v3fs-docview-cta">
            {canEdit ? (
              <button type="button" className="v3fs-btn" onClick={() => setAsDocument((v) => !v)}>
                {asDocument ? "Open the studio" : "View as document"}
              </button>
            ) : null}
            {onRegenerate ? (
              <button type="button" className="v3fs-btn" onClick={() => { onRegenerate(); onClose(); }}>
                {artifact.stale ? "Regenerate — evidence changed" : "Regenerate"}
              </button>
            ) : null}
            <button type="button" className="v3fs-btn" onClick={onClose} aria-label="Close">Close</button>
          </div>
        </header>

        <div className="v3fs-docview-b">
          {grounding.length ? (
            <details className="v3fs-disc v3fs-disc-sm v3fs-ground">
              <summary>
                <span className="v3fs-disc-l">Grounded in<em>{grounding.length}</em></span>
                <span className="v3fs-disc-hint">
                  {(() => {
                    const convs = grounding.filter((g) => g.kind === "conversation").length;
                    const docs = grounding.filter((g) => g.kind === "document").length;
                    return [
                      convs ? `${convs} conversation${convs === 1 ? "" : "s"}` : null,
                      docs ? `${docs} document${docs === 1 ? "" : "s"}` : null,
                    ].filter(Boolean).join(" · ");
                  })()}
                </span>
                <span className="v3fs-disc-c" aria-hidden="true" />
              </summary>
              <div className="v3fs-disc-b">
                {grounding.map((entry_) => (
                  <div key={entry_.uri} className="v3fs-ground-row">
                    <span className={`v3fs-tag ${entry_.kind === "document" ? "gn" : "ev"}`}>{entry_.kind}</span>
                    <div className="v3fs-row-g">
                      <div className="v3fs-row-n">{entry_.label}</div>
                      <div className="v3fs-row-m">{entry_.relation} · {entry_.uri}</div>
                    </div>
                  </div>
                ))}
                <button type="button" className="v3fs-a" onClick={() => {
                  const node = {
                    "@context": SEMANTIC_CONTEXT,
                    "@id": resourceUri(program.id, "artifact", artifact.id),
                    "@type": artifactFabioType(artifact.id),
                    "dcterms:title": artifact.title,
                    citations: citationGraph(program),
                  };
                  try { void navigator.clipboard.writeText(JSON.stringify(node, null, 2)); } catch { /* ignore */ }
                }}>
                  Copy as JSON-LD
                </button>
              </div>
            </details>
          ) : null}

          {studioActive && entry && draft ? (
            <entry.Component doc={draft} onChange={(next) => { setDraft(next); setDirty(true); }} />
          ) : (
            <>
              {blocks.length === 0 ? <p className="v3fs-empty">No document body yet — generate it first.</p> : null}
              {blocks.map((lines, blockIndex) => (
                <div key={blockIndex} className="v3fs-docview-blk">
                  {lines.map((line, lineIndex) =>
                    line.kind === "h" ? <h3 key={lineIndex}>{line.text}</h3>
                      : line.kind === "li" ? <div key={lineIndex} className="v3fs-docview-li">{line.text}</div>
                        : <p key={lineIndex}>{line.text}</p>,
                  )}
                </div>
              ))}
            </>
          )}
        </div>

        {studioActive && (dirty || savedTick) ? (
          <footer className="v3fs-stu-savebar">
            <span>{savedTick && !dirty ? "Saved — attested to the trail ✓" : "You've edited this document."}</span>
            {dirty ? (
              <div className="v3fs-dec-cta">
                <button type="button" className="v3fs-btn pri" disabled={saving} onClick={() => void save()}>
                  {saving ? "Saving…" : "Save & attest"}
                </button>
                <button type="button" className="v3fs-btn" disabled={saving}
                  onClick={() => { setDraft(storedDoc); setDirty(false); }}>
                  Discard edits
                </button>
              </div>
            ) : null}
          </footer>
        ) : null}
      </div>
    </>
  );
}
