/**
 * Prototype → external project export. The Prototype Build is stored as ONE
 * self-contained HTML document (data.prototypeBuild.html). That runs anywhere,
 * but a build team or a coding agent wants a real directory structure to work
 * in — separate markup, styles and script, the seed fixtures, the design tokens,
 * and a README that explains what it is and how to run it. This splits the
 * single document into that structure and zips it, so the prototype becomes
 * externally modifiable with normal tooling instead of a lone blob.
 */
import JSZip from "jszip";
import { resolveTheme, meridianStylesheet, type PrototypeTheme } from "@shared/prototypeDesignSystem.ts";

export interface PrototypeProjectInput {
  html: string;
  title?: string;
  programName?: string;
  screens?: Array<Record<string, unknown>>;
  /** experienceDesign.theme — the governed design tokens. */
  theme?: Record<string, unknown> | null;
  /** prototypePack — fixtures (seed records) + scope contract. */
  pack?: Record<string, unknown> | null;
}

/**
 * Split the single self-contained document into index.html + styles.css +
 * app.js. Inline <style>/<script> blocks are lifted out (in document order, so
 * script dependencies are preserved) and replaced with external references. The
 * script is loaded `defer` so it still runs after the DOM is parsed — identical
 * timing to an inline script at the end of <body>.
 */
export function splitPrototypeHtml(html: string): { indexHtml: string; css: string; js: string } {
  if (typeof DOMParser === "undefined") return { indexHtml: html, css: "", js: "" };
  const doc = new DOMParser().parseFromString(html, "text/html");
  const css = Array.from(doc.querySelectorAll("style")).map((s) => s.textContent || "").join("\n\n").trim();
  /**
   * A DATA ISLAND IS NOT CODE, AND MUST NOT BE LIFTED INTO ONE.
   *
   * The assembled build carries its seeded records as a
   * `<script type="application/json">` block that the page reads at load. It is
   * a script ELEMENT and it is not a script: concatenated into `app.js` it is a
   * syntax error that takes the whole renderer with it, and removed from
   * `index.html` it takes every row in the application. Only executable blocks
   * move; the island stays exactly where the document put it.
   */
  const executable = (s: Element) => {
    const type = (s.getAttribute("type") || "").toLowerCase();
    return !s.getAttribute("src") && (!type || type === "text/javascript" || type === "module" || type === "application/javascript");
  };
  const js = Array.from(doc.querySelectorAll("script"))
    .filter(executable)
    .map((s) => s.textContent || "").filter(Boolean).join("\n\n").trim();
  doc.querySelectorAll("style").forEach((s) => s.remove());
  doc.querySelectorAll("script").forEach((s) => { if (executable(s)) s.remove(); });
  if (css) {
    const link = doc.createElement("link");
    link.setAttribute("rel", "stylesheet");
    link.setAttribute("href", "styles.css");
    (doc.head || doc.documentElement).appendChild(link);
  }
  if (js) {
    const sc = doc.createElement("script");
    sc.setAttribute("src", "app.js");
    sc.setAttribute("defer", "");
    (doc.body || doc.documentElement).appendChild(sc);
  }
  const indexHtml = `<!doctype html>\n${doc.documentElement.outerHTML}\n`;
  return { indexHtml, css, js };
}

function buildReadme(input: PrototypeProjectInput, has: { css: boolean; js: boolean; fixtures: boolean; tokens: boolean }): string {
  const name = input.programName || input.title || "Prototype";
  const screens = (input.screens || []).map((s) => {
    const n = typeof s.name === "string" ? s.name : typeof s.id === "string" ? s.id : "";
    const p = typeof s.purpose === "string" ? s.purpose : "";
    return n ? `- **${n}**${p ? ` — ${p}` : ""}` : "";
  }).filter(Boolean);
  const scope = input.pack && typeof input.pack.scopeContract === "string" ? input.pack.scopeContract : "";
  const lines: string[] = [
    `# ${name} — prototype`,
    "",
    "A clickable prototype generated by AURA Flow, exported as an editable project. It is a static web app — no build step, no backend.",
    "",
    "## Run it",
    "",
    "Open `index.html` in any browser, or serve the folder:",
    "",
    "```sh",
    "npx serve .        # or: python3 -m http.server",
    "```",
    "",
    "## Files",
    "",
    "- `index.html` — the app markup and screens",
    ...(has.css ? ["- `styles.css` — this prototype's screen styles"] : []),
    "- `meridian.css` — the Meridian design system (appearance layer: tokens + `.m-*` component patterns). Link it and use the `.m-*` classes to inherit the house look.",
    ...(has.js ? ["- `app.js` — in-page navigation and interactions"] : []),
    ...(has.tokens ? ["- `design-tokens.json` — the governed theme (brand/ink/surface, semantics, type, spacing, radius) — the source to re-skin from"] : []),
    ...(has.fixtures ? ["- `fixtures.json` — the seed records the screens are populated with"] : []),
  ];
  if (screens.length) {
    lines.push("", "## Screens", "", ...screens);
  }
  if (scope) {
    lines.push("", "## Scope", "", scope);
  }
  lines.push(
    "",
    "## Modifying it",
    "",
    "Edit the files directly, or hand the folder to a coding agent. The styles are token-driven — change `:root` in `styles.css` (or `design-tokens.json` as the source of truth) to re-skin without touching screens. Anything marked *simulated* in the UI is a demo stub, not a live integration.",
    "",
  );
  return lines.join("\n");
}

/** Assemble the full file map for the external project. */
export function buildPrototypeProject(input: PrototypeProjectInput): Record<string, string> {
  const { indexHtml, css, js } = splitPrototypeHtml(input.html);
  const files: Record<string, string> = { "index.html": indexHtml };
  if (css) files["styles.css"] = css;
  if (js) files["app.js"] = js;
  // Meridian — the governed design system — always travels with the export, and
  // the exported tokens default to it (a sparse/absent theme still yields a
  // complete, coherent set). `meridian.css` is the appearance layer a coding
  // agent can apply to re-skin the prototype to the house system.
  const tokens = resolveTheme(input.theme as Partial<PrototypeTheme> | null);
  files["meridian.css"] = meridianStylesheet(tokens);
  files["design-tokens.json"] = `${JSON.stringify(tokens, null, 2)}\n`;
  const hasTokens = true;
  const fixtures = input.pack && Array.isArray(input.pack.fixtures) ? input.pack.fixtures : null;
  const hasFixtures = !!(fixtures && fixtures.length);
  if (hasFixtures) files["fixtures.json"] = `${JSON.stringify(fixtures, null, 2)}\n`;
  files["README.md"] = buildReadme(input, { css: !!css, js: !!js, fixtures: hasFixtures, tokens: hasTokens });
  return files;
}

/** A filesystem-safe folder/base name for the export. */
export function projectSlug(programName?: string): string {
  const base = (programName || "prototype").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return `${base || "prototype"}-prototype`;
}

/**
 * The inverse of splitPrototypeHtml — fold an edited project back into ONE
 * self-contained document. The `styles.css` <link> becomes an inline <style>
 * and the `app.js` <script src> becomes an inline <script>, so the result
 * renders standalone in the sandboxed preview again. If the index.html is
 * already flattened (inline style/script), it passes through unchanged.
 */
export function reassemblePrototypeHtml(indexHtml: string, css: string, js: string): string {
  if (typeof DOMParser === "undefined") return indexHtml;
  const doc = new DOMParser().parseFromString(indexHtml, "text/html");
  if (css) {
    const link = Array.from(doc.querySelectorAll('link[rel="stylesheet"]'))
      .find((l) => /(^|\/)styles\.css$/i.test(l.getAttribute("href") || ""));
    const style = doc.createElement("style");
    style.textContent = css;
    if (link) link.replaceWith(style);
    else (doc.head || doc.documentElement).appendChild(style);
  }
  if (js) {
    const src = Array.from(doc.querySelectorAll("script[src]"))
      .find((s) => /(^|\/)app\.js$/i.test(s.getAttribute("src") || ""));
    const script = doc.createElement("script");
    script.textContent = js;
    if (src) src.replaceWith(script);
    else (doc.body || doc.documentElement).appendChild(script);
  }
  return `<!doctype html>\n${doc.documentElement.outerHTML}\n`;
}

const MAX_IMPORT_BYTES = 800_000;

/**
 * Read an externally-edited prototype back in — either the `.zip` project this
 * studio exports, or a single self-contained `.html`. Returns the reassembled,
 * self-contained document plus any warnings (external URLs / unresolved local
 * files that won't work in the sandboxed preview). It does NOT write anything —
 * the caller loads it into the editor to propose the change.
 */
export async function importPrototypeProject(file: File): Promise<{ html: string; warnings: string[] }> {
  const warnings: string[] = [];
  const name = file.name.toLowerCase();
  let html: string;
  if (name.endsWith(".zip")) {
    const zip = await JSZip.loadAsync(file);
    const byBase = (base: string) => Object.values(zip.files)
      .find((f) => !f.dir && (f.name.split("/").pop() || "").toLowerCase() === base);
    const idx = byBase("index.html");
    if (!idx) throw new Error("No index.html found in the zip.");
    const indexHtml = await idx.async("string");
    const cssEntry = byBase("styles.css");
    const jsEntry = byBase("app.js");
    const css = cssEntry ? await cssEntry.async("string") : "";
    const js = jsEntry ? await jsEntry.async("string") : "";
    html = reassemblePrototypeHtml(indexHtml, css, js);
  } else if (name.endsWith(".html") || name.endsWith(".htm")) {
    html = await file.text();
  } else {
    throw new Error("Import a .zip project or a single .html file.");
  }
  if (html.length > MAX_IMPORT_BYTES) {
    throw new Error(`That prototype is too large (${Math.round(html.length / 1024)} KB) — keep it under ${MAX_IMPORT_BYTES / 1024} KB.`);
  }
  if (/<(?:link|script)[^>]+(?:href|src)=["']https?:\/\//i.test(html)) {
    warnings.push("References external URLs — those won't load in the sandboxed preview. Inline them for a self-contained prototype.");
  }
  if (/<link[^>]+href=["'](?!https?:|data:|#)[^"']+\.css/i.test(html) || /<script[^>]+src=["'](?!https?:|data:)[^"']+\.js/i.test(html)) {
    warnings.push("Still links to local files we couldn't inline (only styles.css and app.js are merged) — flatten extra files before import.");
  }
  return { html, warnings };
}

/** Zip the file map (under a top-level folder) and trigger a download. */
export async function downloadPrototypeZip(files: Record<string, string>, baseName: string): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder(baseName) || zip;
  for (const [name, content] of Object.entries(files)) folder.file(name, content);
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${baseName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
