/**
 * Prototype → external project export. The Prototype Build is stored as ONE
 * self-contained HTML document (data.prototypeBuild.html). That runs anywhere,
 * but a build team or a coding agent wants a real directory structure to work
 * in — separate markup, styles and script, the seed fixtures, the design tokens,
 * and a README that explains what it is and how to run it. This splits the
 * single document into that structure and zips it, so the prototype becomes
 * externally modifiable with normal tooling instead of a lone blob.
 */
import JSZip from "jszip";

export interface PrototypeProjectInput {
  html: string;
  title?: string;
  programName?: string;
  screens?: Array<Record<string, unknown>>;
  /** experienceDesign.theme — the governed design tokens. */
  theme?: Record<string, unknown> | null;
  /** prototypePack — fixtures (seed records) + scope contract. */
  pack?: Record<string, unknown> | null;
}

/**
 * Split the single self-contained document into index.html + styles.css +
 * app.js. Inline <style>/<script> blocks are lifted out (in document order, so
 * script dependencies are preserved) and replaced with external references. The
 * script is loaded `defer` so it still runs after the DOM is parsed — identical
 * timing to an inline script at the end of <body>.
 */
export function splitPrototypeHtml(html: string): { indexHtml: string; css: string; js: string } {
  if (typeof DOMParser === "undefined") return { indexHtml: html, css: "", js: "" };
  const doc = new DOMParser().parseFromString(html, "text/html");
  const css = Array.from(doc.querySelectorAll("style")).map((s) => s.textContent || "").join("\n\n").trim();
  const js = Array.from(doc.querySelectorAll("script"))
    .filter((s) => !s.getAttribute("src"))
    .map((s) => s.textContent || "").filter(Boolean).join("\n\n").trim();
  doc.querySelectorAll("style").forEach((s) => s.remove());
  doc.querySelectorAll("script").forEach((s) => { if (!s.getAttribute("src")) s.remove(); });
  if (css) {
    const link = doc.createElement("link");
    link.setAttribute("rel", "stylesheet");
    link.setAttribute("href", "styles.css");
    (doc.head || doc.documentElement).appendChild(link);
  }
  if (js) {
    const sc = doc.createElement("script");
    sc.setAttribute("src", "app.js");
    sc.setAttribute("defer", "");
    (doc.body || doc.documentElement).appendChild(sc);
  }
  const indexHtml = `<!doctype html>\n${doc.documentElement.outerHTML}\n`;
  return { indexHtml, css, js };
}

function buildReadme(input: PrototypeProjectInput, has: { css: boolean; js: boolean; fixtures: boolean; tokens: boolean }): string {
  const name = input.programName || input.title || "Prototype";
  const screens = (input.screens || []).map((s) => {
    const n = typeof s.name === "string" ? s.name : typeof s.id === "string" ? s.id : "";
    const p = typeof s.purpose === "string" ? s.purpose : "";
    return n ? `- **${n}**${p ? ` — ${p}` : ""}` : "";
  }).filter(Boolean);
  const scope = input.pack && typeof input.pack.scopeContract === "string" ? input.pack.scopeContract : "";
  const lines: string[] = [
    `# ${name} — prototype`,
    "",
    "A clickable prototype generated by ATOS Flow, exported as an editable project. It is a static web app — no build step, no backend.",
    "",
    "## Run it",
    "",
    "Open `index.html` in any browser, or serve the folder:",
    "",
    "```sh",
    "npx serve .        # or: python3 -m http.server",
    "```",
    "",
    "## Files",
    "",
    "- `index.html` — the app markup and screens",
    ...(has.css ? ["- `styles.css` — the design system + component styles"] : []),
    ...(has.js ? ["- `app.js` — in-page navigation and interactions"] : []),
    ...(has.tokens ? ["- `design-tokens.json` — the governed theme (brand/accent/neutral, type, spacing, radius)"] : []),
    ...(has.fixtures ? ["- `fixtures.json` — the seed records the screens are populated with"] : []),
  ];
  if (screens.length) {
    lines.push("", "## Screens", "", ...screens);
  }
  if (scope) {
    lines.push("", "## Scope", "", scope);
  }
  lines.push(
    "",
    "## Modifying it",
    "",
    "Edit the files directly, or hand the folder to a coding agent. The styles are token-driven — change `:root` in `styles.css` (or `design-tokens.json` as the source of truth) to re-skin without touching screens. Anything marked *simulated* in the UI is a demo stub, not a live integration.",
    "",
  );
  return lines.join("\n");
}

/** Assemble the full file map for the external project. */
export function buildPrototypeProject(input: PrototypeProjectInput): Record<string, string> {
  const { indexHtml, css, js } = splitPrototypeHtml(input.html);
  const files: Record<string, string> = { "index.html": indexHtml };
  if (css) files["styles.css"] = css;
  if (js) files["app.js"] = js;
  const hasTokens = !!(input.theme && Object.keys(input.theme).length);
  if (hasTokens) files["design-tokens.json"] = `${JSON.stringify(input.theme, null, 2)}\n`;
  const fixtures = input.pack && Array.isArray(input.pack.fixtures) ? input.pack.fixtures : null;
  const hasFixtures = !!(fixtures && fixtures.length);
  if (hasFixtures) files["fixtures.json"] = `${JSON.stringify(fixtures, null, 2)}\n`;
  files["README.md"] = buildReadme(input, { css: !!css, js: !!js, fixtures: hasFixtures, tokens: hasTokens });
  return files;
}

/** A filesystem-safe folder/base name for the export. */
export function projectSlug(programName?: string): string {
  const base = (programName || "prototype").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return `${base || "prototype"}-prototype`;
}

/** Zip the file map (under a top-level folder) and trigger a download. */
export async function downloadPrototypeZip(files: Record<string, string>, baseName: string): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder(baseName) || zip;
  for (const [name, content] of Object.entries(files)) folder.file(name, content);
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${baseName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
